// =====================================================================
// bridge.src.js - native bridge for the Capacitor Android shell.
//
// Exposes the same public API the web app expects (Bridge.send /
// Bridge.setHandlers / Bridge.receive, window.handleAppResponse), so
// controller.js and ftms_integration.js don't need to know a native
// layer is involved at all. BLE scan/connect, local storage, app exit,
// keep-screen-on and the status bar are all handled here natively.
//
// Bundled with esbuild into www/bridge.js (see package.json). Every
// other module (state.js, view.js, api.js, controller.js,
// ftms_integration.js, debug*.js) is copied through unchanged.
// =====================================================================

import { BleClient } from '@capacitor-community/bluetooth-le';
import { Preferences } from '@capacitor/preferences';
import { App } from '@capacitor/app';
import { StatusBar, Style } from '@capacitor/status-bar';
import { KeepAwake } from '@capacitor-community/keep-awake';

var FTMS_SERVICE = '00001826-0000-1000-8000-00805f9b34fb';
var FTMS_CHAR    = '00002ad1-0000-1000-8000-00805f9b34fb';
var WORKOUT_PREFIX = 'workout_';

var Bridge = (function () {
  'use strict';

  var handlers = {};
  var bleReady = false;
  var connectedId = null;      // currently connected device id (MAC on Android)
  var connecting = false;      // guards against overlapping connect() calls
  var skipNextFrame = false;   // true right after (re)connecting
  var intentionalDisconnect = false;
  var previousData = null;     // last FTMS csv sent, so duplicate frames can be skipped (never reset)
  var foundDevices = {};       // id -> name, accumulated during a scan

  function setHandlers(map) { handlers = map; }

  function fire(action, data) {
    var fn = handlers[action];
    if (fn) fn(Object.assign({ action: action }, data || {}));
    else console.warn('[bridge] no handler for', action);
  }

  // -- boot: ask BLE permission once, restore token, kick off autoLogin --
  async function init() {
    try {
      await BleClient.initialize({ androidNeverForLocation: true });
      bleReady = true;
    } catch (e) {
      console.error('[bridge] BLE init failed', e);
    }
    try { await KeepAwake.keepAwake(); } catch (e) { /* not fatal */ }
    try {
      await StatusBar.setBackgroundColor({ color: '#000000' });
      await StatusBar.setStyle({ style: Style.Dark });
    } catch (e) { /* no-op on platforms without a status bar */ }

    App.addListener('backButton', function () {
      // Deliberate no-op: the hardware back button uses the platform
      // default everywhere. Revisit if a screen ever needs its own
      // back-button handling.
    });

    var stored = await Preferences.get({ key: 'token' });
    fire('autoLogin', { token: stored.value || '' });
  }

  // -- outgoing: actions the web app asks the native layer to perform --
  async function send(action, data) {
    data = data || {};
    switch (action) {
      case 'loginResult': return onLoginResult(data);
      case 'scan': return startScan();
      case 'stopScan': return stopScan();
      case 'connect': return connect(data.deviceId);
      case 'reconnect': return connect(connectedId);
      case 'disconnect': return disconnect();
      case 'saveData': return saveData(data);
      case 'uploadAck': return uploadAck(data);
      case 'exit': return App.exitApp();
      default:
        console.warn('[bridge] unhandled outgoing action', action, data);
    }
  }

  // -- login / offline upload queue -------------------------------------
  // Only a genuine credential/token rejection (success:false with no
  // offline flag) clears the stored token. A connectivity failure
  // (offline:true) leaves the token alone, so autologin can just retry
  // once the network is back instead of forcing a manual re-login after
  // a temporary network blip.
  async function onLoginResult(data) {
    if (data.success) {
      await Preferences.set({ key: 'token', value: data.token || '' });
      await reuploadStoredWorkouts(data.token);
    } else if (!data.offline) {
      await Preferences.set({ key: 'token', value: '' });
    }
  }

  async function reuploadStoredWorkouts(token) {
    var keys = (await Preferences.keys()).keys || [];
    for (var i = 0; i < keys.length; i++) {
      var k = keys[i];
      if (k.indexOf(WORKOUT_PREFIX) !== 0) continue;
      var stored = await Preferences.get({ key: k });
      if (!stored.value) continue;
      fire('uploadWorkout', { token: token, workout: k, data: stored.value });
    }
  }

  async function saveData(data) {
    // Store under the workout's own unique tag (e.g.
    // "workout_20260808153000", generated by ftms_integration.js's
    // workoutTag()) rather than a fixed key, so multiple offline workouts
    // don't collide and overwrite each other.
    await Preferences.set({
      key: data.workout,
      value: typeof data.data === 'string' ? data.data : JSON.stringify(data.data)
    });
    fire('saveAck', {});
  }

  async function uploadAck(data) {
    await Preferences.remove({ key: data.workout });
    fire('tagCleared', { workout: data.workout });
  }

  // -- scan ---------------------------------------------------------------
  // No `services: [FTMS_SERVICE]` filter here, on purpose: a service-UUID
  // scan filter only matches devices that advertise their full service
  // list in the small (~31-byte) advertisement packet itself, and plenty
  // of BLE peripherals only expose their services after a GATT connection.
  // Scanning with no filter and matching by device name instead, then
  // checking for the FTMS characteristic once connected, is the reliable
  // approach here.
  async function startScan() {
    if (!bleReady) { fire('scanResult', { devices: [] }); return; }
    foundDevices = {};
    try {
      await BleClient.requestLEScan(
        {},
        function (result) {
          var name = result.device.name || result.localName || '';
          if (name.indexOf('XEBEX') === -1) return; // only Xebex rowers advertise this name
          if (foundDevices[result.device.deviceId]) return;
          foundDevices[result.device.deviceId] = name;
          emitScanResult();
        }
      );
    } catch (e) {
      console.error('[bridge] scan failed', e);
      fire('scanResult', { devices: [] });
    }
  }

  function emitScanResult() {
    var devices = Object.keys(foundDevices).map(function (id) {
      return { id: id + ' ' + foundDevices[id] }; // controller.js splits "id name" on whitespace
    });
    fire('scanResult', { devices: devices });
  }

  async function stopScan() {
    try { await BleClient.stopLEScan(); } catch (e) { /* already stopped */ }
  }

  // -- connect / disconnect ------------------------------------------------
  // `connecting` guards against overlapping connect() calls: controller.js's
  // reconnect loop fires Bridge.send('reconnect') every 5s without waiting
  // for a previous attempt to settle, and the Android GATT stack handles
  // two concurrent connect() calls to the same device badly. This flag
  // makes sure only one attempt is ever in flight at a time.
  //
  // The 8000ms connect timeout below has margin above the ~3s a real
  // on-device connection takes, so it tolerates slower conditions without
  // giving up too eagerly.
  async function connect(deviceId) {
    if (!deviceId) { fire('connectResult', { success: false, error: 'no device' }); return; }
    if (connecting) { return; }
    connecting = true;
    try {
      await stopScan();
      await BleClient.connect(deviceId, onUnexpectedDisconnect, { timeout: 8000 });
      connectedId = deviceId;
      skipNextFrame = true; // see onFtmsFrame: the rower's first push is a stale cached reading, not live data
      await BleClient.startNotifications(deviceId, FTMS_SERVICE, FTMS_CHAR, onFtmsFrame);
      fire('connectResult', { success: true });
    } catch (e) {
      fire('connectResult', { success: false, error: String(e && e.message || e) });
    } finally {
      connecting = false;
    }
  }

  function onUnexpectedDisconnect() {
    if (intentionalDisconnect) { intentionalDisconnect = false; return; }
    fire('disconnected', {});
  }

  async function disconnect() {
    if (!connectedId) return;
    intentionalDisconnect = true;
    try { await BleClient.disconnect(connectedId); } catch (e) { /* already gone */ }
    connectedId = null;
  }

  // -- FTMS frames ----------------------------------------------------------
  // The raw GATT notification is exactly 20 bytes, which is exactly what
  // ftms_integration.js's parsePacket() expects (it indexes up to b[19]
  // and requires b.length >= 20) - no trimming needed. As a sanity check,
  // byte[16] lands on the heart-rate field, and it reads 255
  // (parsePacket's "no HR sensor" sentinel) when no strap is connected,
  // confirming the byte alignment is correct.
  function onFtmsFrame(value) {
    // value is a DataView backed by a shared/pooled ArrayBuffer - must
    // respect byteOffset/byteLength, not just value.buffer, or this can
    // read bytes belonging to a different notification.
    var bytes = new Uint8Array(value.buffer, value.byteOffset, value.byteLength);
    var csv = Array.prototype.join.call(bytes, ',');

    // Right after subscribing, the rower immediately pushes one
    // notification carrying its last-held reading from whenever it was
    // last used - frozen, and potentially stale by minutes or a full
    // disconnect/reconnect. ftms_integration.js treats any spm>0 packet as
    // "rowing started", so that stale first push would otherwise kick off
    // a phantom session the instant the app connects, before the user has
    // touched the rower. Dropping just that first push (peripherals
    // commonly reply with a cached value the instant you subscribe) avoids
    // that without touching the shared parsing code.
    if (skipNextFrame) { skipNextFrame = false; return; }

    if (csv === previousData) return; // skip duplicate frames (previousData is never reset)
    previousData = csv;
    fire('ftmsData', { data: csv });
  }

  // -- incoming: JSON messages delivered from the native side --------------
  //
  // Expects { action: "...", ... }. FTMS frames don't arrive through here -
  // they reach the app through fire('ftmsData', ...) in onFtmsFrame above,
  // already carrying an explicit action. Kept for API parity with the
  // web-facing Bridge interface, even though nothing currently calls it.
  function receive(json) {
    if (!json) return;
    var msg;
    try { msg = typeof json === 'string' ? JSON.parse(json) : json; }
    catch (e) {
      console.warn('[bridge] dropping unparseable message:', String(json).slice(0, 80));
      return;
    }
    if (!msg || !msg.action) { console.warn('[bridge] message with no action'); return; }
    var fn = handlers[msg.action];
    if (fn) fn(msg); else console.warn('Unknown action:', msg.action);
  }

  init();

  return { send: send, setHandlers: setHandlers, receive: receive };
})();

window.Bridge = Bridge;
window.handleAppResponse = Bridge.receive; // exposed for API parity; nothing currently calls it
